</$objtype/mkfile

TARG=hdl
OFILES=\
	main.$O \
	lex.$O \
	y.tab.$O \
	ast.$O \
	sym.$O \
	fsm.$O \
	fold.$O \
	meta.$O \
	pipe.$O \
	typc.$O \
	semc.$O \
	set.$O \
	vout.$O \
	sysf.$O \

BIN=/$objtype/bin

YFILES=parse.y
HFILES=dat.h fns.h

</sys/src/cmd/mkone

lex.$O: y.tab.c

semc.$O: semc0.c semc1.c semc2.c

YFLAGS=$YFLAGS -D1 -v
