</$objtype/mkfile

TARG=vlt
OFILES=\
	main.$O \
	lex.$O \
	y.tab.$O \
	ast.$O \
	sym.$O \
	fsm.$O \
	fold.$O \
	typc.$O \
	semc.$O \
	set.$O \
	vout.$O \

BIN=/$objtype/bin

YFILES=parse.y
HFILES=dat.h fns.h

</sys/src/cmd/mkone

lex.$O: y.tab.c

YFLAGS=$YFLAGS -D1 -v
