</$objtype/mkfile

TARG=vlt
OFILES=\
	main.$O \
	lex.$O \
	y.tab.$O \
	ast.$O \
	fold.$O \
	cfg.$O \
	aijubrd.$O \
	sysf.$O \
	lint.$O \
	de10.$O \

BIN=/$objtype/bin

YFILES=parse.y
HFILES=dat.h fns.h

</sys/src/cmd/mkone

lex.$O: y.tab.c

YFLAGS=$YFLAGS -D1 -v

aijubrd.$O: ps7.h
