void *emalloc(int);
void decode(void);
void symbrun(void);
void symbinit(void);
void simrun(void);
void rlinit(void);
ushort rlread(ushort, ushort);
void rlwrite(ushort, ushort, ushort);
ushort uniread(ushort, ushort);
void uniwrite(ushort, ushort, ushort);
