void *emalloc(int);
void decode(void);
void symbrun(void);
void symbinit(void);
void simrun(void);
void rlinit(void);
int rlread(ushort, ushort);
int rlwrite(ushort, ushort, ushort);
int uniread(int, ushort);
int uniwrite(int, ushort, ushort);
int kw11read(ushort, ushort);
int kw11write(ushort, ushort, ushort);
int kw11irq(void);
int consread(ushort, ushort);
int conswrite(ushort, ushort, ushort);
void devinit(void);
