void *emalloc(int);
void decode(void);
void symbrun(void);
void symbinit(void);
void simrun(void);
void rlinit(void);
int rlread(ushort, ushort);
int rlwrite(ushort, ushort, ushort);
int uniread(int, ushort);
int uniwrite(int, ushort, ushort);
